JULIO CESAR ZAMPIERI RM 98772

In [60]:
import pandas as pd
import numpy as np

In [61]:
tabela = pd.read_csv("./CSV/brasileirao.csv", encoding='latin1')

In [62]:
tabela.T

,0,1,2,3,4,5,6,7,8,9,...,417,418,419,420,421,422,423,424,425,426
season,2003,2003,2003,2003,2003,2003,2003,2003,2003,2003,...,2023,2023,2023,2023,2023,2023,2023,2023,2023,2023
place,1,2,3,4,5,6,7,8,9,10,...,10,12,13,14,15,16,17,18,19,20
acronym,CRU,SAN,SAO,SCA,CFC,CAM,INT,FLA,GOI,PAR,...,FOR,CUI,COR,CRU,VAS,ECB,SAN,GOI,CFC,AMG
team,Cruzeiro,Santos,SaoPaulo,SaoCaetano,Coritiba,Atletico-MG,Internacional,Flamengo,Goias,Parana,...,Fortaleza,Cuiaba,Corinthians,Cruzeiro,Vasco,Bahia,Santos,Goias,Coritiba,America-MG
points,100,87,78,74,73,72,72,66,65,65,...,54,51,50,47,45,44,43,38,30,24
played,46,46,46,46,46,46,46,46,46,46,...,38,38,38,38,38,38,38,38,38,38
won,31,25,22,19,21,19,20,18,18,18,...,15,14,12,11,12,12,11,9,8,5
draw,7,12,12,14,10,15,10,12,11,11,...,9,9,14,14,9,8,10,11,6,9
loss,8,9,12,13,15,12,16,16,17,17,...,14,15,12,13,17,18,17,18,24,24
goals_for,102,93,81,53,67,76,59,66,78,85,...,45,40,47,35,41,50,39,36,41,42
goals_against,47,60,67,37,58,62,57,73,63,75,...,44,39,48,32,51,53,64,53,73,81
goals_diff,55,33,14,16,9,14,2,-7,15,10,...,1,1,-1,3,-10,-3,-25,-17,-32,-39

# PERGUNTAS BRASILEIRÃO 2003 ~ 2023

1.Quem venceu a temporada de 2008?<br>
2.Qual time fez o maior número de pontos de todos os tempos? Especifique a temporada e o número de pontos.<br>
3.Qual time teve o melhor aproveitamento de gols? Especifique a temporada e o número.<br>
4.Qual time sofreu mais gols em todos os tempos? Especifique a temporada e o número de gols.<br>
5.Qual time perdeu mais partida? Especifique a temporada.<br>
6.Qual time teve o pior aproveitamento de gols? Especifique a temporada e o número.<br>
7.Quem venceu a temporada de 2023?<br>
8.Quem venceu a temporada de 2018?<br>
9.Quem teve mais derrotas em 2020?<br>
10.Quem teve mais vitórias em 2009?<br>

In [63]:
# 1.Quem venceu a temporada de 2008?

winner2008 = tabela[['season', 'place', 'team', 'acronym']] #puxando dados da tabela
winner_2008 = winner2008.loc[(winner2008['season'] == 2008) & (winner2008['place'] == 1) & (winner2008['team']) & (winner2008['acronym'])]

print(f"{winner_2008}")

     season  place      team acronym
109    2008      1  SaoPaulo     SAO

In [64]:
# 2.Qual time fez o maior número de pontos de todos os tempos? Especifique a temporada e o número de pontos.

pointsall = tabela.sort_values(by='points', ascending=False) #puxando dados da tabela
mostpoints = pointsall.iloc[0]

print(mostpoints)

season               2003
place                   1
acronym               CRU
team             Cruzeiro
points                100
played                 46
won                    31
draw                    7
loss                    8
goals_for             102
goals_against          47
goals_diff             55
Name: 0, dtype: object

In [65]:
# 3.Qual time teve o melhor aproveitamento de gols? Especifique a temporada e o número.

saldoall = tabela.sort_values(by='goals_diff', ascending=False) #puxando dados da tabela
mostsaldo = saldoall.iloc[0]

print(mostsaldo)

season               2003
place                   1
acronym               CRU
team             Cruzeiro
points                100
played                 46
won                    31
draw                    7
loss                    8
goals_for             102
goals_against          47
goals_diff             55
Name: 0, dtype: object

In [66]:
# 4.Qual time sofreu mais gols em todos os tempos? Especifique a temporada e o número de gols.

sofreuall = tabela.sort_values(by='goals_against', ascending=False) #puxando dados da tabela
mostsofrido = sofreuall.iloc[0]

print(mostsofrido)

season               2005
place                  21
acronym               PAY
team             Paysandu
points                 41
played                 42
won                    12
draw                    5
loss                   25
goals_for              63
goals_against          92
goals_diff            -29
Name: 68, dtype: object

In [67]:
# 5.Qual time perdeu mais partida? Especifique a temporada.

lostall = tabela.sort_values(by='loss', ascending=False) #puxando dados da tabela
mostlost = lostall.iloc[0]

print(mostlost)

season                 2007
place                    20
acronym                 AFC
team             America-RN
points                   17
played                   38
won                       4
draw                      5
loss                     29
goals_for                24
goals_against            80
goals_diff              -56
Name: 108, dtype: object

In [68]:
# 6.Qual time teve o pior aproveitamento de gols? Especifique a temporada e o número.

saldopiorall = tabela.sort_values(by='goals_diff', ascending=True) #puxando dados da tabela
mostpiorsaldo = saldopiorall.iloc[0]

print(mostpiorsaldo)

season              2013
place                 20
acronym              NAU
team             Nautico
points                20
played                38
won                    5
draw                   5
loss                  28
goals_for             22
goals_against         79
goals_diff           -57
Name: 228, dtype: object

In [69]:
# 7.Quem venceu a temporada de 2023?

winner2023 = tabela[['season', 'place', 'team', 'acronym']] #puxando dados da tabela
winner_2023 = winner2023.loc[(winner2023['season'] == 2023) & (winner2023['place'] == 1) & (winner2023['team']) & (winner2023['acronym'])]

print(f"{winner_2023}")

     season  place       team acronym
408    2023      1  Palmeiras     PAL

In [70]:
# 8.Quem venceu a temporada de 2018?

winner2018 = tabela[['season', 'place', 'team', 'acronym']] #puxando dados da tabela
winner_2018 = winner2018.loc[(winner2018['season'] == 2018) & (winner2018['place'] == 1) & (winner2018['team']) & (winner2018['acronym'])]

print(f"{winner_2018}")

     season  place       team acronym
308    2018      1  Palmeiras     PAL

In [71]:
# 9.Quem teve mais derrotas em 2020?
data_2020 = tabela[tabela['season'] == 2020]
brvalue = data_2020.sort_values(by='loss', ascending=False)
timemaisderrotas = brvalue.iloc[0]

print(timemaisderrotas)

season               2020
place                  20
acronym               BOT
team             Botafogo
points                 27
played                 38
won                     5
draw                   12
loss                   21
goals_for              32
goals_against          62
goals_diff            -30
Name: 367, dtype: object

In [74]:
# 10.Quem teve mais vitórias em 2009?

data_2009 = tabela[tabela['season'] == 2009]
brvalue = data_2009.sort_values(by='won', ascending=False)
timemaisvitorias = brvalue.iloc[0]

print(timemaisvitorias)

season               2009
place                   1
acronym               FLA
team             Flamengo
points                 67
played                 38
won                    19
draw                   10
loss                    9
goals_for              58
goals_against          44
goals_diff             14
Name: 129, dtype: object